<?php

function agreement_login_user($op, &$edit, &$account, $category = NULL)
{
    if ($op == 'login') {
        global $user;
        if (isset($_GET['destination'])) {
            unset($_GET['destination']);
            unset($_REQUEST['destination']);
        }
        $expried_date = db_fetch_object(db_query("SELECT * FROM {agreement_login} WHERE uid = $user->uid"))->expired_date;

        if ($expried_date === false || time() > $expried_date) {
            drupal_goto('/myform');
        } else {
            drupal_goto('/node/1');
        }
    }
}
function agreement_login_menu()
{
    $items = array();
    $items['myform'] = array(
        'title' => t('terms of use'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('myform_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}


# our drupal form "form builder" function
function myform_form($form_state)
{

    $html = "<p></p>The services that Microsoft provides to you are subject to the following Terms of Use ('TOU'). Microsoft reserves the right to update the TOU at any time without notice to you. The most current version of the TOU can be reviewed by clicking on the 'Terms of Use' hypertext link located at the bottom of our Web pages.</p>";

    $form['mymarkup'] = array(
        '#type' => 'markup',
        '#value' => $html,
    );
    $link_logout = "window.location='logout';";
    $markup = '<input type="button" value="Disagree" onclick="' . $link_logout . '" />';

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Agree',
    );
    $form['myformelement'] = array(
        '#type' => 'markup',
        '#value' => $markup
    );
    return $form;
}

# our drupal form submit handler (using a submit handler
# given by the default naming convention, i.e.,
# 'firstmodule_form1' plus '_submit')
function myform_form_submit($form, &$form_state)
{
    global $user;
    $nextYear =  strtotime("next year");
    $r = db_query("SELECT * FROM {agreement_login} WHERE uid = $user->uid");
    if ($r->num_rows == 0) {
        db_query("INSERT INTO {agreement_login} (uid, expired_date)  VALUES (%d, '%d')", $user->uid, $nextYear);
    } else {
        db_query("UPDATE {agreement_login} SET expired_date= $nextYear WHERE uid= $user->uid");
    }
    drupal_set_message(t('The form has been submitted.'));
    drupal_goto('/node/1');
    // Here is where your submit functionality should go. 
}
